### ISSUE TITLE
darknet2caffe.py ValueError: invalid literal for int() with base 10: '-1,-4'

### ISSUE THREAD

**Issue by mhnatiuk** [marvis/pytorch-caffe-darknet-convert#15]
Hi,
im using darknet2caffe.py to convert classic yolov2 model, but it seems that it's not compatible with yoloV2:
` ~/pytorch-caffe-darknet-convert $ python darknet2caffe.py ~/darknet/cfg/yolo.cfg ~/darknet/yolo.weights yolo.prototxt yolo.caffemodel
unknow layer type reorg 
Traceback (most recent call last):
  File "darknet2caffe.py", line 350, in <module>
    darknet2caffe(cfgfile, weightfile, protofile, caffemodel)
  File "darknet2caffe.py", line 10, in darknet2caffe
    net_info = cfg2prototxt(cfgfile)
  File "darknet2caffe.py", line 251, in cfg2prototxt
    prev_layer_id = layer_id + int(block['layers'])
ValueError: invalid literal for int() with base 10: '-1,-4'
`
The problem lies in this lines of yolo cfg:
`[route]
layers=-9

[reorg]
stride=2

[route]
layers=-1,-3
`

any suggestions how to avoid/fix this? This would be really helpful as im trying to deploy this on TensorRT and converting to caffe model seems the only working solution now [ but TensorRT 3.0 promises to eat tensorflow models]

**Comment by marvis** [comment]
You need to define action of convert route layer with two inputs https://github.com/marvis/pytorch-caffe-darknet-convert/blob/master/darknet2caffe.py#L250-L25. Such as 

        elif block['type'] == 'route':
            from_layers = block['layers'].split(',')
            if len(from_layers) == 1:
                prev_layer_id = layer_id + int(from_layers[0])
                bottom = topnames[prev_layer_id]
                topnames[layer_id] = bottom
                layer_id = layer_id + 1
            else:
                prev_layer_id1 = layer_id + int(from_layers[0])
                prev_layer_id2 = layer_id + int(from_layers[1])
                bottom1 = topnames[prev_layer_id1]
                bottom2= topnames[prev_layer_id2]
                concat_layer = OrderedDict()
                concat_layer['bottom'] = [bottom1, bottom2]
                if block.has_key('name'):
                    concat_layer['top'] = block['name']
                    concat_layer['name'] = block['name']
                else:
                    concat_layer['top'] = 'layer%d-concat' % layer_id
                    concat_layer['name'] = 'layer%d-concat' % layer_id
                concat_layer['type'] = 'concat'
                layers.append(concat_layer)
                bottom = concat_layer['top']
                topnames[layer_id] = bottom
                layer_id = layer_id+1

**Comment by imoinuddin** [comment]
@marvis 

I tried this suggestion with a minor change, changing concat_layer['type'] = 'concat' to 'Concat'
I still seem to run into issues as running the script then prints out something like:

I1019 12:38:15.193336 29043 layer_factory.hpp:77] Creating layer layer28-concat
I1019 12:38:15.193342 29043 net.cpp:84] Creating Layer layer28-concat
I1019 12:38:15.193346 29043 net.cpp:406] layer28-concat <- layer17-conv_layer17-act_0_split_1
I1019 12:38:15.193351 29043 net.cpp:406] layer28-concat <- layer25-conv
I1019 12:38:15.193356 29043 net.cpp:380] layer28-concat -> layer28-concat
**F1019 12:38:15.193368 29043 concat_layer.cpp:42] Check failed: top_shape[j] == bottom[i]->shape(j) (26 vs. 13) All inputs must have the same shape, except at concat_axis.**
*** Check failure stack trace: ***
Aborted (core dumped)

My original cfg contains :  
[route]
layers=-1,-3

Any suggestions on what I should be doing differently?

**Comment by marvis** [comment]
@imoinuddin Is it because of the concat method in caffe different from that in darknet?

**Comment by thudepwcp13** [comment]
@imoinuddin @mhnatiuk @marvis I have the same question too. Does anyone solve it? Please help me.

**Comment by ysh329** [comment]
same issue

**Comment by quhezheng** [comment]
@imoinuddin Because this code doesn't convert darknet layer 'reorg‘ which would cut down the size by half. 
@marvis Please add the code to treat 'reorg'

**Comment by ysh329** [comment]
@quhezheng I added `reorg` layer [here](https://github.com/ysh329/pytorch-caffe-darknet-convert).

**Comment by quhezheng** [comment]
@ysh329 Thanks a lot for your reply. Your implementation does not comply with darknet's reorg layer. I added a reorg layer in caffe and ported darknet's code into it. This is a perfect solution

**Comment by ysh329** [comment]
@quhezheng Great! 👍  Where can I find your code and how to use 😀

**Comment by quhezheng** [comment]
@ysh329 [https://github.com/quhezheng/caffe_yolo_v2](url)
The caffe 'reorg' layer is pushed well.
 I will upload the py script later to convert cfg to prototxt with 'reorg' layer support.

**Comment by ysh329** [comment]
@mhnatiuk eh 404 🤣

**Comment by quhezheng** [comment]
@ysh329 updated!

**Comment by ysh329** [comment]
@quhezheng eh, I have a question: After conversion darknet YOLOv2 model to caffe, I'm not sure whether region layer has parameters in `caffemodel` (except anchors or other hyper-parameters)?

**Comment by Teoge** [comment]
@quhezheng Hi, thanks for sharing! Did you finish your python script of converting cfg to prototxt with 'reorg' layer support? Really appreciate it if you could share it with us!
