### ISSUE TITLE
ValueError: need more than 1 value to unpack

### ISSUE THREAD

**Issue by alanz2015** [marvis/pytorch-caffe-darknet-convert#17]
Hi,

When I use the following command to convert pre-trained DARKNET yolo cfg & weights to .prototxt and .caffemodel files

python darknet2caffe.py ~/workspace/darknet/pre-trained/yolo_2class_box11.cfg ~/workspace/darknet/pre-trained/yolo_2class_box11_3000.weights ~/workspace/darknet/pre-trained/yolo_test.prototxt ~/workspace/darknet/pre-trained/yolo_test.caffemodel

I encountered the failure as following:
Traceback (most recent call last):
  File "darknet2caffe.py", line 351, in <module>
    darknet2caffe(cfgfile, weightfile, protofile, caffemodel)
  File "darknet2caffe.py", line 11, in darknet2caffe
    net_info = cfg2prototxt(cfgfile)
  File "darknet2caffe.py", line 108, in cfg2prototxt
    blocks = parse_cfg(cfgfile)
  File "/home/sky-alanz/workspace/pytorch-caffe-darknet-convert/cfg.py", line 27, in parse_cfg
    key,value = line.split('=')
ValueError: need more than 1 value to unpack

What is the problem? P.S. the test files can be downloaded from http://guanghan.info/blog/en/my-works/train-yolo/

Regards,
Alan Zhang

**Comment by marvis** [comment]
Seems the parsing line is not the "key = value" format

**Comment by pocaris** [comment]
@alanz2015 
I met the same error when I downloaded the .cfg file and run the script. 
Finally, I copy the lines in .cfg file manually and create a new one, it works.
I think it should be format problems when directly use the provided .cfg file.

**Comment by richardharmadi** [comment]
@alanz2015 I encountered the same issue, and when I see the .cfg file i downloaded, it was in the HTML format. 

You need to make sure the .cfg file is correct like in here https://github.com/pjreddie/darknet/blob/master/cfg/tiny-yolo-voc.cfg
