### ISSUE TITLE
KeyError: 'ExpandBackward'

### ISSUE THREAD

**Issue by AITTSMD** [marvis/pytorch-caffe-darknet-convert#18]
@marvis Hi,thanks  for your greate job. When I convert resnet18 in pytorch to caffe,I get an error like this KeyError: 'ExpandBackward'.I refer pytorch2caffe and find that 'ExpandBackward' is not in layer_dict.So what the 'ExpandBackward'  is.

**Comment by manlinting** [comment]
I also have the problem. it was because the pytorch version as you train and you eval not match.

**Comment by MichaelYSC** [comment]
@manlinting How to solve this problem?

**Comment by oya163** [comment]
Yes, same problem here, when I used vgg16 as well.

**Comment by MichaelYSC** [comment]
@oya163 Hi, did you solve this problem? I add this layer but there are some bugs.

**Comment by oya163** [comment]
No haven't solved it yet. Have you?

**Comment by MichaelYSC** [comment]
@oya163 No. I will try again. :-)

**Comment by oya163** [comment]
@marvis Which pytorch && python version are you using?

**Comment by manlinting** [comment]
I have not solve this problem, so I still use pytorch 0.2

**Comment by oya163** [comment]
Yes, I also switched to pytorch 0.2. Getting seg fault in pytorch2caffe conversion. Did your conversion go smoothly?

**Comment by oya163** [comment]
Use pytorch=0.2 and torchvision=0.1.8. Error is gone at least.

**Comment by panovr** [comment]
I have the same error:

> Traceback (most recent call last):
  File "pytorch2caffe.py", line 244, in <module>
    pytorch2caffe(input_var, output_var, 'resnet50-pytorch2caffe.prototxt', 'resnet50-pytorch2caffe.caffemodel')
  File "pytorch2caffe.py", line 26, in pytorch2caffe
    net_info = pytorch2prototxt(input_var, output_var)
  File "pytorch2caffe.py", line 216, in pytorch2prototxt
    add_layer(output_var.grad_fn)
  File "pytorch2caffe.py", line 125, in add_layer
    top_name = add_layer(u[0])
  File "pytorch2caffe.py", line 137, in add_layer
    layer['type'] = layer_dict[parent_type]
KeyError: 'ExpandBackward'


pytorch=0.3.0 and torchvision=0.2.0

**Comment by manlinting** [comment]
Does anyone solve this problem?

**Comment by xiaopeng-liao** [comment]
got the same problem here,
pytorch=0.3.1 and torchvision=0.2.0

**Comment by lzhaozi** [comment]
got the same problem here,
pytorch=0.3.1 and torchvision=0.2.1

**Comment by josh-gleason** [comment]
I was able to workaround this problem by installing pytorch 0.2.0 and torchvision 0.1.8 as noted above.

I use virtualenv + pip to manage my python environment. I just created a new virtualenv and installed directly from pytorch git repo.

`pip install git+https://github.com/pytorch/pytorch.git@v0.2.0 torchvision==0.1.8`

Took quite a while to install torch from github but the scripts worked fine after that.
