### ISSUE TITLE
KeyError: 'layer1-conv' in conversion of yolo2 to caffe

### ISSUE THREAD

**Issue by norouzzadeh** [marvis/pytorch-caffe-darknet-convert#26]
I'm using python 3.5 on Ubuntu 16.04. In the conversion of yolo2 to caffe model, using either with or without BN, the darknet2caffe.py gives the following error:

Traceback (most recent call last):
  File "../pytorch-caffe-darknet-convert/darknet2caffe.py", line 350, in <module>
    darknet2caffe(cfgfile, weightfile, protofile, caffemodel)
  File "../pytorch-caffe-darknet-convert/darknet2caffe.py", line 45, in darknet2caffe
    start = load_conv2caffe(buf, start, params[conv_layer_name])
KeyError: 'layer1-conv'

**Comment by qiushenjie** [comment]
Using python2 would help you to solve this problem.

**Comment by PiyalGeorge** [comment]
Not solved when using python 2

**Comment by AntoineGerardeaux** [comment]
same problem, need a fix !

**Comment by AntoineGerardeaux** [comment]
Solved by setup my config with Ubuntu 16.04, cuda 8.0, Python 2.7 and pytorch 0.4.
