### ISSUE TITLE
KeyError: 'ExpandBackward' in pytorch2caffe.py

### ISSUE THREAD

**Issue by padagi20** [marvis/pytorch-caffe-darknet-convert#30]
I am testing with "Convert pytorch -> caffe -> darknet", following the guide document. (https://github.com/marvis/pytorch-caffe-darknet-convert)

1. python main.py -a resnet50-pytorch --pretrained -e ../ImageNet/
2. python pytorch2caffe.py 

Step 1 is works well. I checked same precision between document and my env.
But when I try step2, I found following python Error.
Will not somebody help me?

pytorch version is 0.2.0 and torchvision version is 0.1.8 
--------------------------------------------------------------------------------------------------
..
converting AddmmBackward190
Traceback (most recent call last):
  File "pytorch2caffe.py", line 244, in <module>
    pytorch2caffe(input_var, output_var, 'resnet50-pytorch2caffe.prototxt', 'resnet50-pytorch2caffe.caffemodel')
  File "pytorch2caffe.py", line 77, in pytorch2caffe
    convert_layer(output_var.grad_fn)
  File "pytorch2caffe.py", line 75, in convert_layer
    save_fc2caffe(weights, biases, params[parent_name])
  File "pytorch2caffe.py", line 88, in save_fc2caffe
    fc_param[0].data[...] = weights.numpy()
ValueError: could not broadcast input array from shape (1000,2048) into shape (1000,8192)

**Comment by wldeephi** [comment]
i met the same problems too, have you solved  it ? @padagi20

**Comment by wldeephi** [comment]
OK , I have solved the problem by set the ceil_mode in the pooling_layer to True in caffe/proto/caffe.proto

**Comment by padagi20** [comment]
@wldeephi 
I just read your message.
Actually, I could not solve this.
Thanks.

**Comment by wldeephi** [comment]
@padagi20 ,
in the ''/your_workspace_path/src/caffe/proto/caffe.proto''

message PoolingParameter {
  enum PoolMethod {
    MAX = 0;
    AVE = 1;
    STOCHASTIC = 2;
  }
  optional PoolMethod pool = 1 [default = MAX]; // The pooling method
  // Pad, kernel size, and stride are all given as a single value for equal
  // dimensions in height and width or as Y, X pairs.
  optional uint32 pad = 4 [default = 0]; // The padding size (equal in Y, X)
  optional uint32 pad_h = 9 [default = 0]; // The padding height
  optional uint32 pad_w = 10 [default = 0]; // The padding width
  optional uint32 kernel_size = 2; // The kernel size (square)
  optional uint32 kernel_h = 5; // The kernel height
  optional uint32 kernel_w = 6; // The kernel width
  optional uint32 stride = 3 [default = 1]; // The stride (equal in Y, X)
  optional uint32 stride_h = 7; // The stride height
  optional uint32 stride_w = 8; // The stride width
  enum Engine {
    DEFAULT = 0;
    CAFFE = 1;
    CUDNN = 2;
  }
  optional Engine engine = 11 [default = DEFAULT];
  // If global_pooling then it will pool over the size of the bottom by doing
  // kernel_h = bottom->height and kernel_w = bottom->width
  optional bool global_pooling = 12 [default = false];
  optional bool ceil_mode = 13 [default = true];
""
Here you just change the ''optional bool ceil_mode = 13 [default = true]; '' 
To
 "optional bool ceil_mode = 13 [default = false];" 
then the problem can be solved!

**Comment by ajay-collab** [comment]
I've set the "optional bool ceil_mode = 13 [default = false];" and still facing the same issue. Any idea?
