### ISSUE TITLE
"Error parsing message" when running caffe2darknet.py

### ISSUE THREAD

**Issue by hy9be** [marvis/pytorch-caffe-darknet-convert#35]
I was trying to convert a faster_rcnn model from caffe to darknet and result in the error message below:
```
[libprotobuf ERROR google/protobuf/io/coded_stream.cc:207] A protocol message was rejected because it was too big (more than 67108864 bytes).  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
Traceback (most recent call last):
  File "/home/ubuntu/pytorch-caffe-darknet-convert/caffe2darknet.py", line 348, in <module>
    blocks, data = caffe2darknet(protofile, caffemodel)
  File "/home/ubuntu/pytorch-caffe-darknet-convert/caffe2darknet.py", line 9, in caffe2darknet
    model = parse_caffemodel(caffemodel)
  File "/home/ubuntu/pytorch-caffe-darknet-convert/prototxt.py", line 16, in parse_caffemodel
    model.ParseFromString(fp.read())
google.protobuf.message.DecodeError: Error parsing message
```

**Comment by hy9be** [comment]
If I set the environment variable PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python, it will run but eventually stops at another error:
```
Traceback (most recent call last):
  File "/home/ubuntu/pytorch-caffe-darknet-convert/caffe2darknet.py", line 348, in <module>
    blocks, data = caffe2darknet(protofile, caffemodel)
  File "/home/ubuntu/pytorch-caffe-darknet-convert/caffe2darknet.py", line 19, in caffe2darknet
    net_info = parse_prototxt(protofile)
  File "/home/ubuntu/pytorch-caffe-darknet-convert/prototxt.py", line 79, in parse_prototxt
    layer = parse_block(fp)
  File "/home/ubuntu/pytorch-caffe-darknet-convert/prototxt.py", line 49, in parse_block
    sub_block = parse_block(fp)
  File "/home/ubuntu/pytorch-caffe-darknet-convert/prototxt.py", line 37, in parse_block
    key, value = line.split(':')
ValueError: too many values to unpack
```

**Comment by tkngoutham** [comment]
this worked for me:


_EXPORT_DIR='path/to/expored/model/dir'
with tf.Session(graph=tf.Graph()) as sess:
    tf.saved_model.loader.load(sess, [tf.saved_model.tag_constants.SERVING], _EXPORT_DIR)
    trainable_coll = sess.graph.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES)
    vars = {v.name:sess.run(v.value()) for v in trainable_coll}
