### ISSUE TITLE
ValueError: too many values to unpack

### ISSUE THREAD

**Issue by zenggzh** [marvis/pytorch-caffe-darknet-convert#46]
When I want to convert caffemodel to darknetmodel, it happened.
$ python caffe2darknet.py deploy.prototxt ZF_faster_rcnn_final.caffemodel faster_rcnn_test.cfg ZF_faster_rcnn_final.weights
Loading caffemodel:  ZF_faster_rcnn_final.caffemodel
Traceback (most recent call last):
  File "caffe2darknet.py", line 348, in <module>
    blocks, data = caffe2darknet(protofile, caffemodel)
  File "caffe2darknet.py", line 19, in caffe2darknet
    net_info = parse_prototxt(protofile)
  File "/home/zeng/Desktop/pytorch-caffe-darknet-convert-master/prototxt.py", line 79, in parse_prototxt
    layer = parse_block(fp)
  File "/home/zeng/Desktop/pytorch-caffe-darknet-convert-master/prototxt.py", line 49, in parse_block
    sub_block = parse_block(fp)
  File "/home/zeng/Desktop/pytorch-caffe-darknet-convert-master/prototxt.py", line 37, in parse_block
    key, value = line.split(':')
ValueError: too many values to unpack

**Comment by zenggzh** [comment]
@marvis

**Comment by zenggzh** [comment]
It has solved,and now there is no error. But when i run it, it stop at 'load caffemodel' for a long time without other operation.

**Comment by zhshe** [comment]
ValueError: too many values to unpack .it happened to me.how do you solved it ?

**Comment by zhshe** [comment]
ValueError: too many values to unpack .it happened to me.how did you solve it ?
