### ISSUE TITLE
RunTimeError in detect.py after converting tiny yolo from darknet to caffe

### ISSUE THREAD

**Issue by puffadder** [marvis/pytorch-caffe-darknet-convert#50]
Hi,

I converted tiny yolo v2 from darknet to caffe using the following script:

_python darknet2caffe.py tiny-yolo.cfg yolov2-tiny.weights tiny-yolo.prototxt tiny-yolo.caffemodel_

The weights and cfg file are downloaded from darknet website

After that, I try to run detection on the converted caffemodel using the following command:

_python detect.py tiny-yolo.prototxt tiny-yolo.caffemodel <test image>_

The test image is 416x416 RGB image as expected.

However, I get the following error:

**Loading caffemodel:  tiny-yolo.caffemodel
Traceback (most recent call last):
  File "detect.py", line 47, in <module>
    detect(cfgfile, weightfile, imgfile)
  File "detect.py", line 15, in detect
    m.load_weights(weightfile)
  File "/home/bhargav/pytorch-caffe-darknet-convert/caffenet.py", line 135, in load_weights
    self.models[lname].weight.data.copy_(torch.from_numpy(np.array(lmap[lname].blobs[0].data)))
RuntimeError: The expanded size of the tensor (3) must match the existing size (432) at non-singleton dimension 3**

Not sure what is causing this error. Any help would be greatly appreciated!

Thanks,
Bhargav

**Comment by puffadder** [comment]
Unfortunately no.

**Comment by queryor** [comment]
i meet the same problem.

**Comment by queryor** [comment]
i fix it with changing the code under.
` shape_new = self.models[lname].weight.shape
  self.models[lname].weight.data.copy_(torch.reshape(torch.from_numpy(np.array(lmap[lname].blobs[0].     data)),shape_new))`
