### ISSUE TITLE
YOLOv3-caffe

### ISSUE THREAD

**Issue by darwin1993** [marvis/pytorch-caffe-darknet-convert#53]
Hello, did anyone test the converting YOLOv3 model to caffe?

**Comment by milosgajdos83** [comment]
@darwin1993 I tried to convert tiny yolov3, it's currently broken:

```
unknow layer type yolo
unknow layer type upsample
Traceback (most recent call last):
  File "darknet2caffe.py", line 350, in <module>
    darknet2caffe(cfgfile, weightfile, protofile, caffemodel)
  File "darknet2caffe.py", line 10, in darknet2caffe
    net_info = cfg2prototxt(cfgfile)
  File "darknet2caffe.py", line 251, in cfg2prototxt
    prev_layer_id = layer_id + int(block['layers'])
ValueError: invalid literal for int() with base 10: '-1, 8'
```

**Comment by BingzheWu** [comment]
You can find a solution in this repo https://github.com/BingzheWu/object_detetction_tools/blob/master/nn_model_transform/darknet2caffe.py

**Comment by eric612** [comment]
I have a try in my [project](https://github.com/eric612/MobileNet-YOLO/tree/master/models/darknet_yolov3)

**Comment by Roython** [comment]
when i try transfer yolov3 of darknet to caffe, i got this problem, can anyone tell what can i do?

Traceback (most recent call last):
  File "darknet2caffe.py", line 439, in <module>
    darknet2caffe(cfgfile, weightfile, protofile, caffemodel)
  File "darknet2caffe.py", line 15, in darknet2caffe
    params = net.params  
  File "/****/pycaffe.py", line 68, in _Net_params
    if len(lr.blobs) > 0])
OverflowError: long int too large to convert to int
Bus error (core dumped)
