### ISSUE TITLE
caffe2darknet.py  failed   ValueError: need more than 2 values to unpack

### ISSUE THREAD

**Issue by azuryl** [marvis/pytorch-caffe-darknet-convert#59]
python caffe2darknet.py   SqueezeNet_v1.1.prototxt  squeezenet_v1.1.caffemodel  squeezenet_v1.1.cfg squeezenet_v1.1.weights
Loading caffemodel:  squeezenet_v1.1.caffemodel
name: "conv1"
name: "conv1"
Traceback (most recent call last):
  File "caffe2darknet.py", line 348, in <module>
    blocks, data = caffe2darknet(protofile, caffemodel)
  File "caffe2darknet.py", line 19, in caffe2darknet
    net_info = parse_prototxt(protofile)
  File "/home/jliu/gpt/pytorch-caffe-darknet-convert/prototxt.py", line 84, in parse_prototxt
    layer = parse_block(fp)
  File "/home/jliu/gpt/pytorch-caffe-darknet-convert/prototxt.py", line 38, in parse_block
    key, value,value2,value3,value4 = line.split(':')
ValueError: need more than 2 values to unpack

**Comment by azuryl** [comment]
the model and prototxt from

https://github.com/DeepScale/SqueezeNet/tree/master/SqueezeNet_v1.1
