### ISSUE TITLE
transform from pytorch to caffe failed

### ISSUE THREAD

**Issue by LeonSun0101** [marvis/pytorch-caffe-darknet-convert#60]
/usr/bin/python2.7 /home1/sas/sparse-to-dense/main.py -e -a resnet50 -d deconv3 -m rgbd -s 100 --data nyudepthv2 -b 1
Namespace(arch='resnet50', batch_size=1, criterion='l1', data='nyudepthv2', decoder='deconv3', epochs=15, evaluate=True, lr=0.01, max_depth=-1.0, modality='rgbd', momentum=0.9, num_samples=100, pretrained=True, print_freq=10, resume='', sparsifier='uar', start_epoch=0, weight_decay=0.0001, workers=10)
=> creating data loaders ...
Found 47584 images in train folder.
Found 654 images in val folder.
=> data loaders created.
=> loading best model 'results/nyudepthv2.sparsifier=uar.samples=100.modality=rgbd.arch=resnet50.decoder=deconv3.criterion=l1.lr=0.01.bs=1.pretrained=True/model_best.pth.tar'
/usr/local/lib/python2.7/dist-packages/torch/serialization.py:425: SourceChangeWarning: source code of class 'models.ResNet' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
=> loaded best model (epoch 77)
/usr/local/lib/python2.7/dist-packages/torch/nn/modules/upsampling.py:122: UserWarning: nn.Upsampling is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.Upsampling is deprecated. Use nn.functional.interpolate instead.")
i am alive 0000000000000000000000000000000000000000000000000000
Starting Transform, This will take a while
139715563547936:blob1 was added to blobs
139715563547936:blob1 getting
conv1 was added to layers
139715487722304:conv_blob1 was added to blobs
139715563547936:blob1 getting
139715487722304:conv_blob1 getting
139715487722304:conv_blob1 getting
batch_norm1 was added to layers
139715487722704:batch_norm_blob1 was added to blobs
bn_scale1 was added to layers
139715487722704:batch_norm_blob1 getting
relu1 was added to layers
139715487722704:relu_blob1 was added to blobs
139715487722704:relu_blob1 getting
max_pool1 was added to layers
139715487722624:max_pool_blob1 was added to blobs
139715487722704:relu_blob1 getting
WARNING: the output shape miss match at max_pool1: input torch.Size([1, 64, 114, 152]) output---Pytorch:torch.Size([1, 64, 57, 76])---Caffe:torch.Size([1, 64, 58, 77])
This is caused by the different implementation that ceil mode in caffe and the floor mode in pytorch.
You can add the clip layer in caffe prototxt manually if shape mismatch error is caused in caffe. 
conv2 was added to layers
139715487722384:conv_blob2 was added to blobs
139715487722624:max_pool_blob1 getting
139715487722384:conv_blob2 getting
139715487722384:conv_blob2 getting
batch_norm2 was added to layers
139715487722064:batch_norm_blob2 was added to blobs
bn_scale2 was added to layers
139715487722064:batch_norm_blob2 getting
relu2 was added to layers
139715487722064:relu_blob2 was added to blobs
139715487722064:relu_blob2 getting
conv3 was added to layers
139715487722864:conv_blob3 was added to blobs
139715487722064:relu_blob2 getting
139715487722864:conv_blob3 getting
139715487722864:conv_blob3 getting
batch_norm3 was added to layers
139715487723184:batch_norm_blob3 was added to blobs
bn_scale3 was added to layers
139715487723184:batch_norm_blob3 getting
relu3 was added to layers
139715487723184:relu_blob3 was added to blobs
139715487723184:relu_blob3 getting
conv4 was added to layers
139715487723104:conv_blob4 was added to blobs
139715487723184:relu_blob3 getting
139715487723104:conv_blob4 getting
139715487723104:conv_blob4 getting
batch_norm4 was added to layers
139715487723264:batch_norm_blob4 was added to blobs
bn_scale4 was added to layers
conv5 was added to layers
139715487723424:conv_blob5 was added to blobs
139715487722624:max_pool_blob1 getting
139715487723424:conv_blob5 getting
139715487723424:conv_blob5 getting
batch_norm5 was added to layers
139715487723344:batch_norm_blob5 was added to blobs
bn_scale5 was added to layers
add1 was added to layers
139715487722944:add_blob1 was added to blobs
139715487723264:batch_norm_blob4 getting
139715487723344:batch_norm_blob5 getting
139715487722944:add_blob1 getting
relu4 was added to layers
139715487722944:relu_blob4 was added to blobs
139715487722944:relu_blob4 getting
conv6 was added to layers
139715487722784:conv_blob6 was added to blobs
139715487722944:relu_blob4 getting
139715487722784:conv_blob6 getting
139715487722784:conv_blob6 getting
batch_norm6 was added to layers
139715361931504:batch_norm_blob6 was added to blobs
bn_scale6 was added to layers
139715361931504:batch_norm_blob6 getting
relu5 was added to layers
139715361931504:relu_blob5 was added to blobs
139715361931504:relu_blob5 getting
conv7 was added to layers
139715487723024:conv_blob7 was added to blobs
139715361931504:relu_blob5 getting
139715487723024:conv_blob7 getting
139715487723024:conv_blob7 getting
batch_norm7 was added to layers
139715361931664:batch_norm_blob7 was added to blobs
bn_scale7 was added to layers
139715361931664:batch_norm_blob7 getting
relu6 was added to layers
139715361931664:relu_blob6 was added to blobs
139715361931664:relu_blob6 getting
conv8 was added to layers
139715361931744:conv_blob8 was added to blobs
139715361931664:relu_blob6 getting
139715361931744:conv_blob8 getting
139715361931744:conv_blob8 getting
batch_norm8 was added to layers
139715361931824:batch_norm_blob8 was added to blobs
bn_scale8 was added to layers
add2 was added to layers
139715361931984:add_blob2 was added to blobs
139715361931824:batch_norm_blob8 getting
139715487722944:relu_blob4 getting
139715361931984:add_blob2 getting
relu7 was added to layers
139715361931984:relu_blob7 was added to blobs
139715361931984:relu_blob7 getting
conv9 was added to layers
139715361931424:conv_blob9 was added to blobs
139715361931984:relu_blob7 getting
139715361931424:conv_blob9 getting
139715361931424:conv_blob9 getting
batch_norm9 was added to layers
139715361931344:batch_norm_blob9 was added to blobs
bn_scale9 was added to layers
139715361931344:batch_norm_blob9 getting
relu8 was added to layers
139715361931344:relu_blob8 was added to blobs
139715361931344:relu_blob8 getting
conv10 was added to layers
139715361931904:conv_blob10 was added to blobs
139715361931344:relu_blob8 getting
139715361931904:conv_blob10 getting
139715361931904:conv_blob10 getting
batch_norm10 was added to layers
139715361932304:batch_norm_blob10 was added to blobs
bn_scale10 was added to layers
139715361932304:batch_norm_blob10 getting
relu9 was added to layers
139715361932304:relu_blob9 was added to blobs
139715361932304:relu_blob9 getting
conv11 was added to layers
139715361932224:conv_blob11 was added to blobs
139715361932304:relu_blob9 getting
139715361932224:conv_blob11 getting
139715361932224:conv_blob11 getting
batch_norm11 was added to layers
139715361932384:batch_norm_blob11 was added to blobs
bn_scale11 was added to layers
add3 was added to layers
139715361932544:add_blob3 was added to blobs
139715361932384:batch_norm_blob11 getting
139715361931984:relu_blob7 getting
139715361932544:add_blob3 getting
relu10 was added to layers
139715361932544:relu_blob10 was added to blobs
139715361932544:relu_blob10 getting
conv12 was added to layers
139715361931584:conv_blob12 was added to blobs
139715361932544:relu_blob10 getting
139715361931584:conv_blob12 getting
139715361931584:conv_blob12 getting
batch_norm12 was added to layers
139715361932144:batch_norm_blob12 was added to blobs
bn_scale12 was added to layers
139715361932144:batch_norm_blob12 getting
relu11 was added to layers
139715361932144:relu_blob11 was added to blobs
139715361932144:relu_blob11 getting
conv13 was added to layers
139715361932464:conv_blob13 was added to blobs
139715361932144:relu_blob11 getting
139715361932464:conv_blob13 getting
139715361932464:conv_blob13 getting
batch_norm13 was added to layers
139715361932864:batch_norm_blob13 was added to blobs
bn_scale13 was added to layers
139715361932864:batch_norm_blob13 getting
relu12 was added to layers
139715361932864:relu_blob12 was added to blobs
139715361932864:relu_blob12 getting
conv14 was added to layers
139715361932784:conv_blob14 was added to blobs
139715361932864:relu_blob12 getting
139715361932784:conv_blob14 getting
139715361932784:conv_blob14 getting
batch_norm14 was added to layers
139715361932944:batch_norm_blob14 was added to blobs
bn_scale14 was added to layers
conv15 was added to layers
139715361933104:conv_blob15 was added to blobs
139715361932544:relu_blob10 getting
139715361933104:conv_blob15 getting
139715361933104:conv_blob15 getting
batch_norm15 was added to layers
139715361933024:batch_norm_blob15 was added to blobs
bn_scale15 was added to layers
add4 was added to layers
139715361933264:add_blob4 was added to blobs
139715361932944:batch_norm_blob14 getting
139715361933024:batch_norm_blob15 getting
139715361933264:add_blob4 getting
relu13 was added to layers
139715361933264:relu_blob13 was added to blobs
139715361933264:relu_blob13 getting
conv16 was added to layers
139715361932064:conv_blob16 was added to blobs
139715361933264:relu_blob13 getting
139715361932064:conv_blob16 getting
139715361932064:conv_blob16 getting
batch_norm16 was added to layers
139715361932624:batch_norm_blob16 was added to blobs
bn_scale16 was added to layers
139715361932624:batch_norm_blob16 getting
relu14 was added to layers
139715361932624:relu_blob14 was added to blobs
139715361932624:relu_blob14 getting
conv17 was added to layers
139715361933184:conv_blob17 was added to blobs
139715361932624:relu_blob14 getting
139715361933184:conv_blob17 getting
139715361933184:conv_blob17 getting
batch_norm17 was added to layers
139715361933584:batch_norm_blob17 was added to blobs
bn_scale17 was added to layers
139715361933584:batch_norm_blob17 getting
relu15 was added to layers
139715361933584:relu_blob15 was added to blobs
139715361933584:relu_blob15 getting
conv18 was added to layers
139715361933504:conv_blob18 was added to blobs
139715361933584:relu_blob15 getting
139715361933504:conv_blob18 getting
139715361933504:conv_blob18 getting
batch_norm18 was added to layers
139715361933664:batch_norm_blob18 was added to blobs
bn_scale18 was added to layers
add5 was added to layers
139715361933824:add_blob5 was added to blobs
139715361933664:batch_norm_blob18 getting
139715361933264:relu_blob13 getting
139715361933824:add_blob5 getting
relu16 was added to layers
139715361933824:relu_blob16 was added to blobs
139715361933824:relu_blob16 getting
conv19 was added to layers
139715361932704:conv_blob19 was added to blobs
139715361933824:relu_blob16 getting
139715361932704:conv_blob19 getting
139715361932704:conv_blob19 getting
batch_norm19 was added to layers
139715361933424:batch_norm_blob19 was added to blobs
bn_scale19 was added to layers
139715361933424:batch_norm_blob19 getting
relu17 was added to layers
139715361933424:relu_blob17 was added to blobs
139715361933424:relu_blob17 getting
conv20 was added to layers
139715361933744:conv_blob20 was added to blobs
139715361933424:relu_blob17 getting
139715361933744:conv_blob20 getting
139715361933744:conv_blob20 getting
batch_norm20 was added to layers
139715361934144:batch_norm_blob20 was added to blobs
bn_scale20 was added to layers
139715361934144:batch_norm_blob20 getting
relu18 was added to layers
139715361934144:relu_blob18 was added to blobs
139715361934144:relu_blob18 getting
conv21 was added to layers
139715361934064:conv_blob21 was added to blobs
139715361934144:relu_blob18 getting
139715361934064:conv_blob21 getting
139715361934064:conv_blob21 getting
batch_norm21 was added to layers
139715361934224:batch_norm_blob21 was added to blobs
bn_scale21 was added to layers
add6 was added to layers
139715361934384:add_blob6 was added to blobs
139715361934224:batch_norm_blob21 getting
139715361933824:relu_blob16 getting
139715361934384:add_blob6 getting
relu19 was added to layers
139715361934384:relu_blob19 was added to blobs
139715361934384:relu_blob19 getting
conv22 was added to layers
139715361933344:conv_blob22 was added to blobs
139715361934384:relu_blob19 getting
139715361933344:conv_blob22 getting
139715361933344:conv_blob22 getting
batch_norm22 was added to layers
139715361933984:batch_norm_blob22 was added to blobs
bn_scale22 was added to layers
139715361933984:batch_norm_blob22 getting
relu20 was added to layers
139715361933984:relu_blob20 was added to blobs
139715361933984:relu_blob20 getting
conv23 was added to layers
139715361934304:conv_blob23 was added to blobs
139715361933984:relu_blob20 getting
139715361934304:conv_blob23 getting
139715361934304:conv_blob23 getting
batch_norm23 was added to layers
139715361934704:batch_norm_blob23 was added to blobs
bn_scale23 was added to layers
139715361934704:batch_norm_blob23 getting
relu21 was added to layers
139715361934704:relu_blob21 was added to blobs
139715361934704:relu_blob21 getting
conv24 was added to layers
139715361934624:conv_blob24 was added to blobs
139715361934704:relu_blob21 getting
139715361934624:conv_blob24 getting
139715361934624:conv_blob24 getting
batch_norm24 was added to layers
139715361934784:batch_norm_blob24 was added to blobs
bn_scale24 was added to layers
add7 was added to layers
139715361934944:add_blob7 was added to blobs
139715361934784:batch_norm_blob24 getting
139715361934384:relu_blob19 getting
139715361934944:add_blob7 getting
relu22 was added to layers
139715361934944:relu_blob22 was added to blobs
139715361934944:relu_blob22 getting
conv25 was added to layers
139715361933904:conv_blob25 was added to blobs
139715361934944:relu_blob22 getting
139715361933904:conv_blob25 getting
139715361933904:conv_blob25 getting
batch_norm25 was added to layers
139715361934544:batch_norm_blob25 was added to blobs
bn_scale25 was added to layers
139715361934544:batch_norm_blob25 getting
relu23 was added to layers
139715361934544:relu_blob23 was added to blobs
139715361934544:relu_blob23 getting
conv26 was added to layers
139715361934864:conv_blob26 was added to blobs
139715361934544:relu_blob23 getting
139715361934864:conv_blob26 getting
139715361934864:conv_blob26 getting
batch_norm26 was added to layers
139715361935264:batch_norm_blob26 was added to blobs
bn_scale26 was added to layers
139715361935264:batch_norm_blob26 getting
relu24 was added to layers
139715361935264:relu_blob24 was added to blobs
139715361935264:relu_blob24 getting
conv27 was added to layers
139715361935184:conv_blob27 was added to blobs
139715361935264:relu_blob24 getting
139715361935184:conv_blob27 getting
139715361935184:conv_blob27 getting
batch_norm27 was added to layers
139715361935104:batch_norm_blob27 was added to blobs
bn_scale27 was added to layers
conv28 was added to layers
139715361935024:conv_blob28 was added to blobs
139715361934944:relu_blob22 getting
139715361935024:conv_blob28 getting
139715361935024:conv_blob28 getting
batch_norm28 was added to layers
139711996309744:batch_norm_blob28 was added to blobs
bn_scale28 was added to layers
add8 was added to layers
139715361934464:add_blob8 was added to blobs
139715361935104:batch_norm_blob27 getting
139711996309744:batch_norm_blob28 getting
139715361934464:add_blob8 getting
relu25 was added to layers
139715361934464:relu_blob25 was added to blobs
139715361934464:relu_blob25 getting
conv29 was added to layers
139711996309664:conv_blob29 was added to blobs
139715361934464:relu_blob25 getting
139711996309664:conv_blob29 getting
139711996309664:conv_blob29 getting
batch_norm29 was added to layers
139711996309584:batch_norm_blob29 was added to blobs
bn_scale29 was added to layers
139711996309584:batch_norm_blob29 getting
relu26 was added to layers
139711996309584:relu_blob26 was added to blobs
139711996309584:relu_blob26 getting
conv30 was added to layers
139711996309904:conv_blob30 was added to blobs
139711996309584:relu_blob26 getting
139711996309904:conv_blob30 getting
139711996309904:conv_blob30 getting
batch_norm30 was added to layers
139711996310224:batch_norm_blob30 was added to blobs
bn_scale30 was added to layers
139711996310224:batch_norm_blob30 getting
relu27 was added to layers
139711996310224:relu_blob27 was added to blobs
139711996310224:relu_blob27 getting
conv31 was added to layers
139711996310144:conv_blob31 was added to blobs
139711996310224:relu_blob27 getting
139711996310144:conv_blob31 getting
139711996310144:conv_blob31 getting
batch_norm31 was added to layers
139711996310304:batch_norm_blob31 was added to blobs
bn_scale31 was added to layers
add9 was added to layers
139711996310464:add_blob9 was added to blobs
139711996310304:batch_norm_blob31 getting
139715361934464:relu_blob25 getting
139711996310464:add_blob9 getting
relu28 was added to layers
139711996310464:relu_blob28 was added to blobs
139711996310464:relu_blob28 getting
conv32 was added to layers
139711996309824:conv_blob32 was added to blobs
139711996310464:relu_blob28 getting
139711996309824:conv_blob32 getting
139711996309824:conv_blob32 getting
batch_norm32 was added to layers
139711996309984:batch_norm_blob32 was added to blobs
bn_scale32 was added to layers
139711996309984:batch_norm_blob32 getting
relu29 was added to layers
139711996309984:relu_blob29 was added to blobs
139711996309984:relu_blob29 getting
conv33 was added to layers
139711996310384:conv_blob33 was added to blobs
139711996309984:relu_blob29 getting
139711996310384:conv_blob33 getting
139711996310384:conv_blob33 getting
batch_norm33 was added to layers
139711996310784:batch_norm_blob33 was added to blobs
bn_scale33 was added to layers
139711996310784:batch_norm_blob33 getting
relu30 was added to layers
139711996310784:relu_blob30 was added to blobs
139711996310784:relu_blob30 getting
conv34 was added to layers
139711996310704:conv_blob34 was added to blobs
139711996310784:relu_blob30 getting
139711996310704:conv_blob34 getting
139711996310704:conv_blob34 getting
batch_norm34 was added to layers
139711996310864:batch_norm_blob34 was added to blobs
bn_scale34 was added to layers
add10 was added to layers
139711996311024:add_blob10 was added to blobs
139711996310864:batch_norm_blob34 getting
139711996310464:relu_blob28 getting
139711996311024:add_blob10 getting
relu31 was added to layers
139711996311024:relu_blob31 was added to blobs
139711996311024:relu_blob31 getting
conv35 was added to layers
139711996310064:conv_blob35 was added to blobs
139711996311024:relu_blob31 getting
139711996310064:conv_blob35 getting
139711996310064:conv_blob35 getting
batch_norm35 was added to layers
139711996310624:batch_norm_blob35 was added to blobs
bn_scale35 was added to layers
139711996310624:batch_norm_blob35 getting
relu32 was added to layers
139711996310624:relu_blob32 was added to blobs
139711996310624:relu_blob32 getting
conv36 was added to layers
139711996310944:conv_blob36 was added to blobs
139711996310624:relu_blob32 getting
139711996310944:conv_blob36 getting
139711996310944:conv_blob36 getting
batch_norm36 was added to layers
139711996311344:batch_norm_blob36 was added to blobs
bn_scale36 was added to layers
139711996311344:batch_norm_blob36 getting
relu33 was added to layers
139711996311344:relu_blob33 was added to blobs
139711996311344:relu_blob33 getting
conv37 was added to layers
139711996311264:conv_blob37 was added to blobs
139711996311344:relu_blob33 getting
139711996311264:conv_blob37 getting
139711996311264:conv_blob37 getting
batch_norm37 was added to layers
139711996311424:batch_norm_blob37 was added to blobs
bn_scale37 was added to layers
add11 was added to layers
139711996311584:add_blob11 was added to blobs
139711996311424:batch_norm_blob37 getting
139711996311024:relu_blob31 getting
139711996311584:add_blob11 getting
relu34 was added to layers
139711996311584:relu_blob34 was added to blobs
139711996311584:relu_blob34 getting
conv38 was added to layers
139711996310544:conv_blob38 was added to blobs
139711996311584:relu_blob34 getting
139711996310544:conv_blob38 getting
139711996310544:conv_blob38 getting
batch_norm38 was added to layers
139711996311184:batch_norm_blob38 was added to blobs
bn_scale38 was added to layers
139711996311184:batch_norm_blob38 getting
relu35 was added to layers
139711996311184:relu_blob35 was added to blobs
139711996311184:relu_blob35 getting
conv39 was added to layers
139711996311504:conv_blob39 was added to blobs
139711996311184:relu_blob35 getting
139711996311504:conv_blob39 getting
139711996311504:conv_blob39 getting
batch_norm39 was added to layers
139711996311904:batch_norm_blob39 was added to blobs
bn_scale39 was added to layers
139711996311904:batch_norm_blob39 getting
relu36 was added to layers
139711996311904:relu_blob36 was added to blobs
139711996311904:relu_blob36 getting
conv40 was added to layers
139711996311824:conv_blob40 was added to blobs
139711996311904:relu_blob36 getting
139711996311824:conv_blob40 getting
139711996311824:conv_blob40 getting
batch_norm40 was added to layers
139711996311984:batch_norm_blob40 was added to blobs
bn_scale40 was added to layers
add12 was added to layers
139711996312144:add_blob12 was added to blobs
139711996311984:batch_norm_blob40 getting
139711996311584:relu_blob34 getting
139711996312144:add_blob12 getting
relu37 was added to layers
139711996312144:relu_blob37 was added to blobs
139711996312144:relu_blob37 getting
conv41 was added to layers
139711996311104:conv_blob41 was added to blobs
139711996312144:relu_blob37 getting
139711996311104:conv_blob41 getting
139711996311104:conv_blob41 getting
batch_norm41 was added to layers
139711996311744:batch_norm_blob41 was added to blobs
bn_scale41 was added to layers
139711996311744:batch_norm_blob41 getting
relu38 was added to layers
139711996311744:relu_blob38 was added to blobs
139711996311744:relu_blob38 getting
conv42 was added to layers
139711996312064:conv_blob42 was added to blobs
139711996311744:relu_blob38 getting
139711996312064:conv_blob42 getting
139711996312064:conv_blob42 getting
batch_norm42 was added to layers
139711996312464:batch_norm_blob42 was added to blobs
bn_scale42 was added to layers
139711996312464:batch_norm_blob42 getting
relu39 was added to layers
139711996312464:relu_blob39 was added to blobs
139711996312464:relu_blob39 getting
conv43 was added to layers
139711996312384:conv_blob43 was added to blobs
139711996312464:relu_blob39 getting
139711996312384:conv_blob43 getting
139711996312384:conv_blob43 getting
batch_norm43 was added to layers
139711996312544:batch_norm_blob43 was added to blobs
bn_scale43 was added to layers
add13 was added to layers
139711996312704:add_blob13 was added to blobs
139711996312544:batch_norm_blob43 getting
139711996312144:relu_blob37 getting
139711996312704:add_blob13 getting
relu40 was added to layers
139711996312704:relu_blob40 was added to blobs
139711996312704:relu_blob40 getting
conv44 was added to layers
139711996311664:conv_blob44 was added to blobs
139711996312704:relu_blob40 getting
139711996311664:conv_blob44 getting
139711996311664:conv_blob44 getting
batch_norm44 was added to layers
139711996312304:batch_norm_blob44 was added to blobs
bn_scale44 was added to layers
139711996312304:batch_norm_blob44 getting
relu41 was added to layers
139711996312304:relu_blob41 was added to blobs
139711996312304:relu_blob41 getting
conv45 was added to layers
139711996312624:conv_blob45 was added to blobs
139711996312304:relu_blob41 getting
139711996312624:conv_blob45 getting
139711996312624:conv_blob45 getting
batch_norm45 was added to layers
139711996313024:batch_norm_blob45 was added to blobs
bn_scale45 was added to layers
139711996313024:batch_norm_blob45 getting
relu42 was added to layers
139711996313024:relu_blob42 was added to blobs
139711996313024:relu_blob42 getting
conv46 was added to layers
139711996312944:conv_blob46 was added to blobs
139711996313024:relu_blob42 getting
139711996312944:conv_blob46 getting
139711996312944:conv_blob46 getting
batch_norm46 was added to layers
139711996313104:batch_norm_blob46 was added to blobs
bn_scale46 was added to layers
conv47 was added to layers
139711996313264:conv_blob47 was added to blobs
139711996312704:relu_blob40 getting
139711996313264:conv_blob47 getting
139711996313264:conv_blob47 getting
batch_norm47 was added to layers
139711996313184:batch_norm_blob47 was added to blobs
bn_scale47 was added to layers
add14 was added to layers
139711996313424:add_blob14 was added to blobs
139711996313104:batch_norm_blob46 getting
139711996313184:batch_norm_blob47 getting
139711996313424:add_blob14 getting
relu43 was added to layers
139711996313424:relu_blob43 was added to blobs
139711996313424:relu_blob43 getting
conv48 was added to layers
139711996312224:conv_blob48 was added to blobs
139711996313424:relu_blob43 getting
139711996312224:conv_blob48 getting
139711996312224:conv_blob48 getting
batch_norm48 was added to layers
139711996312784:batch_norm_blob48 was added to blobs
bn_scale48 was added to layers
139711996312784:batch_norm_blob48 getting
relu44 was added to layers
139711996312784:relu_blob44 was added to blobs
139711996312784:relu_blob44 getting
conv49 was added to layers
139711996313344:conv_blob49 was added to blobs
139711996312784:relu_blob44 getting
139711996313344:conv_blob49 getting
139711996313344:conv_blob49 getting
batch_norm49 was added to layers
139711673057360:batch_norm_blob49 was added to blobs
bn_scale49 was added to layers
139711673057360:batch_norm_blob49 getting
relu45 was added to layers
139711673057360:relu_blob45 was added to blobs
139711673057360:relu_blob45 getting
conv50 was added to layers
139711996313504:conv_blob50 was added to blobs
139711673057360:relu_blob45 getting
139711996313504:conv_blob50 getting
139711996313504:conv_blob50 getting
batch_norm50 was added to layers
139711673057600:batch_norm_blob50 was added to blobs
bn_scale50 was added to layers
add15 was added to layers
139711996312864:add_blob15 was added to blobs
139711673057600:batch_norm_blob50 getting
139711996313424:relu_blob43 getting
139711996312864:add_blob15 getting
relu46 was added to layers
139711996312864:relu_blob46 was added to blobs
139711996312864:relu_blob46 getting
conv51 was added to layers
139711673057680:conv_blob51 was added to blobs
139711996312864:relu_blob46 getting
139711673057680:conv_blob51 getting
139711673057680:conv_blob51 getting
batch_norm51 was added to layers
139711673057520:batch_norm_blob51 was added to blobs
bn_scale51 was added to layers
139711673057520:batch_norm_blob51 getting
relu47 was added to layers
139711673057520:relu_blob47 was added to blobs
139711673057520:relu_blob47 getting
conv52 was added to layers
139711673057760:conv_blob52 was added to blobs
139711673057520:relu_blob47 getting
139711673057760:conv_blob52 getting
139711673057760:conv_blob52 getting
batch_norm52 was added to layers
139711673058080:batch_norm_blob52 was added to blobs
bn_scale52 was added to layers
139711673058080:batch_norm_blob52 getting
relu48 was added to layers
139711673058080:relu_blob48 was added to blobs
139711673058080:relu_blob48 getting
conv53 was added to layers
139711673058000:conv_blob53 was added to blobs
139711673058080:relu_blob48 getting
139711673058000:conv_blob53 getting
139711673058000:conv_blob53 getting
batch_norm53 was added to layers
139711673058160:batch_norm_blob53 was added to blobs
bn_scale53 was added to layers
add16 was added to layers
139711673058320:add_blob16 was added to blobs
139711673058160:batch_norm_blob53 getting
139711996312864:relu_blob46 getting
139711673058320:add_blob16 getting
relu49 was added to layers
139711673058320:relu_blob49 was added to blobs
139711673058320:relu_blob49 getting
conv54 was added to layers
139711673057440:conv_blob54 was added to blobs
139711673058320:relu_blob49 getting
139711673057440:conv_blob54 getting
139711673057440:conv_blob54 getting
batch_norm54 was added to layers
139711673057920:batch_norm_blob54 was added to blobs
bn_scale54 was added to layers
Traceback (most recent call last):
  File "/home1/sas/sparse-to-dense/main.py", line 315, in <module>
    main()
  File "/home1/sas/sparse-to-dense/main.py", line 101, in main
    validate(val_loader, model, checkpoint['epoch'], write_to_file=False)
  File "/home1/sas/sparse-to-dense/main.py", line 246, in validate
    pytorch_to_caffe.trans_net(model, input, name)
  File "/home1/sas/sparse-to-dense/pytorch_to_caffe.py", line 444, in trans_net
    out = net.forward(input_var)
  File "/home1/sas/sparse-to-dense/models.py", line 234, in forward
    x = self.decoder(x)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home1/sas/sparse-to-dense/models.py", line 54, in forward
    x = self.layer1(x)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/batchnorm.py", line 66, in forward
    exponential_average_factor, self.eps)
  File "/home1/sas/sparse-to-dense/pytorch_to_caffe.py", line 380, in __call__
    out=self.obj(self.raw,*args,**kwargs)
  File "/home1/sas/sparse-to-dense/pytorch_to_caffe.py", line 261, in _batch_norm
    bottom_blobs = [log.blobs(input)]
  File "/home1/sas/sparse-to-dense/pytorch_to_caffe.py", line 73, in blobs
    print("{}:{} getting".format(var, self._blobs[var]))
KeyError: 139711673058240

Process finished with exit code 1

**Comment by Casablancaaa** [comment]
i have met the same problem. have you solve it?

**Comment by Casablancaaa** [comment]
@LeonSun0101
